"""add imdb_id fields

Revision ID: 2c61f662ca9e
Revises: 16e78af9e5bf
Create Date: 2025-12-23 19:42:09.593945

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2c61f662ca9e"
down_revision: Union[str, None] = "16e78af9e5bf"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("movie", sa.Column("imdb_id", sa.String(), nullable=True))
    op.add_column("show", sa.Column("imdb_id", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("show", "imdb_id")
    op.drop_column("movie", "imdb_id")
    # ### end Alembic commands ###
