"""add music tables

Revision ID: 6679fc11aa8f
Revises: 2c61f662ca9e
Create Date: 2026-02-07 22:01:54.813204

"""
from typing import Sequence, Union

from alembic import op
import fastapi_users_db_sqlalchemy.generics
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# Reference the existing quality enum type (created in initial migration)
quality_enum = postgresql.ENUM('uhd', 'fullhd', 'hd', 'sd', 'unknown', name='quality', create_type=False)


# revision identifiers, used by Alembic.
revision: str = '6679fc11aa8f'
down_revision: Union[str, None] = '2c61f662ca9e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('artist',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('external_id', sa.String(), nullable=False),
    sa.Column('metadata_provider', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('overview', sa.String(), nullable=False),
    sa.Column('library', sa.String(), nullable=False),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('disambiguation', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('external_id', 'metadata_provider')
    )
    op.create_table('album',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('artist_id', sa.Uuid(), nullable=False),
    sa.Column('external_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('album_type', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['artist_id'], ['artist.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('artist_id', 'external_id')
    )
    op.create_table('album_file',
    sa.Column('album_id', sa.Uuid(), nullable=False),
    sa.Column('torrent_id', sa.Uuid(), nullable=True),
    sa.Column('file_path_suffix', sa.String(), nullable=False),
    sa.Column('quality', quality_enum, nullable=False),
    sa.ForeignKeyConstraint(['album_id'], ['album.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['torrent_id'], ['torrent.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('album_id', 'file_path_suffix')
    )
    op.create_table('album_request',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('album_id', sa.Uuid(), nullable=False),
    sa.Column('wanted_quality', quality_enum, nullable=False),
    sa.Column('min_quality', quality_enum, nullable=False),
    sa.Column('requested_by_id', fastapi_users_db_sqlalchemy.generics.GUID(), nullable=True),
    sa.Column('authorized', sa.Boolean(), nullable=False),
    sa.Column('authorized_by_id', fastapi_users_db_sqlalchemy.generics.GUID(), nullable=True),
    sa.ForeignKeyConstraint(['album_id'], ['album.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['authorized_by_id'], ['user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['requested_by_id'], ['user.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('album_id', 'wanted_quality')
    )
    op.create_table('track',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('album_id', sa.Uuid(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('external_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['album_id'], ['album.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('album_id', 'number')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('track')
    op.drop_table('album_request')
    op.drop_table('album_file')
    op.drop_table('album')
    op.drop_table('artist')
    # ### end Alembic commands ###
